//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChevalCour
    {
        public System.Guid CHEVALCOURS_id { get; set; }
        public System.Guid CHEVAL_id { get; set; }
        public System.Guid TYPECOURS_id { get; set; }
        public System.Guid NIVEAU_id { get; set; }
    
        public virtual Cheval Cheval { get; set; }
        public virtual Niveau Niveau { get; set; }
        public virtual TypeCour TypeCour { get; set; }
    }
}
